// Writes admin-app/schema.yml — the sections and fields editors see in the
// admin app — from the data-cms annotations in src/index.html. Run after
// changing annotations (then redeploy the admin app):
//
//   npm run cms:schema

import { readFile, writeFile } from 'node:fs/promises';
import { schema } from './template.mjs';
import { PAGES } from './content.mjs';

const SITE_URL = 'https://onegridenergies.com';

const template = await readFile('src/index.html', 'utf8');
const scopes = schema(template);

// Hints for fields whose purpose is not obvious from the page.
const FIELD_HINTS = {
  whatsapp_link: 'WhatsApp link the button opens, e.g. https://wa.me/2347015613314?text=Hello',
  plan_name: 'Used to pre-select the plan in the quote form; keep it identical to an entry in "Preferred plan options".',
  video_label: 'Read aloud by screen readers, e.g. "Watch OnePlastic video".',
  map_embed_url: 'Google Maps embed link (Share → Embed a map → copy the src value).',
  email_link: 'Usually mailto: followed by the email address.',
  icon: 'A symbol, emoji or SVG code shown with this item.'
};

const seoFields = {
  name: 'seo', label: 'Search & sharing', widget: 'object', collapsed: true, fields: [
    { name: 'title', label: 'Browser tab / search title', widget: 'string' },
    { name: 'description', label: 'Search description', widget: 'text', hint: 'About 150 characters, shown in search results and link previews.' }
  ]
};
const introFields = {
  name: 'intro', label: 'Intro video', widget: 'object', collapsed: true, fields: [
    { name: 'video', label: 'Video (MP4)', widget: 'file', hint: 'Upload a video, or paste a Cloudinary .mp4 link.' },
    { name: 'poster', label: 'Poster image', widget: 'image', hint: 'Shown while the video loads.' },
    { name: 'label', label: 'Label', widget: 'string' },
    { name: 'title', label: 'Title', widget: 'string' },
    { name: 'subtitle', label: 'Subtitle', widget: 'text' }
  ]
};

// The admin app treats fields as required unless told otherwise; most of this
// content may legitimately be empty, so fields are optional unless marked.
function finalize(fields) {
  return fields.map(field => {
    const result = { ...field };
    if (FIELD_HINTS[result.name] && !result.hint) result.hint = FIELD_HINTS[result.name];
    if (result.fields) result.fields = finalize(result.fields);
    else if (!('required' in result)) result.required = false;
    return result;
  });
}

function pageFields(name) {
  const fields = (scopes[name] ?? []).filter(field => field.name !== 'intro');
  return finalize([seoFields, introFields, ...fields]);
}

const config = {
  site_url: SITE_URL,
  collections: [
    {
      name: 'pages',
      label: 'Pages',
      label_singular: 'Page',
      description: 'Text, photos and lists on each page. Saved changes go live after the site rebuilds (a few minutes).',
      files: PAGES.map(page => ({
        name: page.name,
        label: page.label,
        file: `content/${page.name}.json`,
        fields: pageFields(page.name)
      }))
    },
    {
      name: 'settings',
      label: 'Site settings',
      description: 'Contact details, social links and the footer, shown on every page.',
      files: [{
        name: 'site',
        label: 'Contact details, social links & footer',
        file: 'content/site.json',
        fields: finalize(scopes.site ?? [])
      }]
    }
  ]
};

// ── minimal YAML writer (strings are JSON-quoted, which YAML accepts) ────────
function yaml(value, indent = '') {
  if (Array.isArray(value)) {
    if (!value.length) return ' []';
    return value.map(item => {
      if (item && typeof item === 'object') {
        const body = yaml(item, `${indent}  `).replace(/^\n\s*/, '');
        return `\n${indent}- ${body}`;
      }
      return `\n${indent}- ${scalar(item)}`;
    }).join('');
  }
  if (value && typeof value === 'object') {
    return Object.entries(value).map(([key, item]) => {
      if (item && typeof item === 'object') return `\n${indent}${key}:${yaml(item, `${indent}  `)}`;
      return `\n${indent}${key}: ${scalar(item)}`;
    }).join('');
  }
  return ` ${scalar(value)}`;
}

function scalar(value) {
  if (typeof value === 'boolean' || typeof value === 'number') return String(value);
  return /^[A-Za-z0-9_./-]+$/.test(value) && !/^(true|false|null|yes|no|on|off|\d.*)$/i.test(value)
    ? value
    : JSON.stringify(value);
}

const header = `# Admin app: the content sections and the fields editors see.
# Generated by scripts/cms/generate-schema.mjs from the data-cms annotations in src/index.html —
# don't edit by hand; run \`npm run cms:schema\` instead. Changes apply after the app is redeployed.
`;
await writeFile('admin-app/schema.yml', `${header}\n${yaml(config).trimStart()}\n`);
console.log('Wrote admin-app/schema.yml');
